# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DrinkShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DrinkShop
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'GoogleSignIn', '~> 5.0'

  target 'DrinkShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DrinkShopUITests' do
    # Pods for testing
  end

end
